### ISSUE TITLE
Can't delete blocks

### ISSUE THREAD

**Issue by blachawk** [ketwaroo/minetest-k-colorblocks#2]
I'm running Minetest 5.8.0 on Windows 10.  After adding blocks from this mod into my game (Minetest Game), the blocks cannot be deleted.  But I can add as many as I want. Please help.

**Comment by ketwaroo** [comment]
ah. It's supposed to be breakable by pickaxe but not punch. That's a "feature". My kids didn't like how they'd accidentally break blocks by punching them.

I checked in the minetest game and it is indeed not breaking as expected. I'll get a fix out as soon as i can figure out what went wrong.

**Comment by ketwaroo** [comment]
fixed in 6b00a9fb5006affaa3e27090d8a6c6062b3b5637
and released in 1.0.5
